
name: Docker build on update to dev-fe
on:
  push:
    branches: [ githubaction-docker-test ]
  pull_request:
    branches: [ githubaction-docker-test ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
      - name: build container image
        run: |
          docker build .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cloudyuta-private-test:dev-fe
